name: buboglaziki
description: Семейное приложение Бубоглазики.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.6.0
  jitsi_meet_flutter_sdk: ^11.6.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  uuid: ^4.3.3
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
