name: Build Android APK

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'
          channel: 'stable'

      - name: Create Flutter platform folders Native
        run: |
          flutter create --project-name buboglaziki --org com.family.buboglaziki .
          
      - name: Configure required Android versions
        run: |
          sed -i 's/flutter.minSdkVersion/26/g' android/app/build.gradle
          sed -i 's/<manifest xmlns:android="http:\/\/schemas.android.com\/apk\/res\/android">/<manifest xmlns:android="http:\/\/schemas.android.com\/apk\/res\/android" xmlns:tools="http:\/\/schemas.android.com\/tools">/g' android/app/src/main/AndroidManifest.xml
          sed -i 's/<application/<application tools:replace="android:label"/g' android/app/src/main/AndroidManifest.xml
          
      - name: Get dependencies
        run: flutter pub get

      - name: Build APK without R8 Minifier
        run: flutter build apk --release --no-shrink

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Buboglaziki-APK
          path: build/app/outputs/flutter-apk/app-release.apk
